name: Auto tagging and release 123

on:
  # Triggers the workflow pull request events but only for the main and develop branch
  pull_request:
    branches:
      - master
      - develop
    types: [closed]
    paths-ignore:
      - '.github/workflows/auto_tagging.yml'

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: auto_tagging
        uses: samarthdd/tagging@v0.3.9
        with:
           GITHUBPAT: ${{secrets.GITHUBPAT}}
           main_branch_name: "master"
           develop_branch_name: "develop"
